package com.trienoir.ultimatetimesheetmaker.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.trienoir.ultimatetimesheetmaker.database.Attendance;

import com.trienoir.ultimatetimesheetmaker.database.AttendanceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig attendanceDaoConfig;

    private final AttendanceDao attendanceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        attendanceDaoConfig = daoConfigMap.get(AttendanceDao.class).clone();
        attendanceDaoConfig.initIdentityScope(type);

        attendanceDao = new AttendanceDao(attendanceDaoConfig, this);

        registerDao(Attendance.class, attendanceDao);
    }
    
    public void clear() {
        attendanceDaoConfig.getIdentityScope().clear();
    }

    public AttendanceDao getAttendanceDao() {
        return attendanceDao;
    }

}
